---
- name: Install Metricbeat
  hosts: webservers
  become: yes
  tasks:
  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb
  
  - name: install metricbeat
    command: sudo dpkg -i metricbeat-7.4.0-amd64.deb
  
  - name: enable and configure
    command: sudo metricbeat modules enable docker
  
  - name: setup metricbeat
    command: metricbeat setup
 
  - name: start metricbeat
    command: service metricbeat start
